allowBuilds:
  "@parcel/watcher": true
  better-sqlite3: true
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude: []
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver
overrides:
  drizzle-orm: 1.0.0-rc.4
